export const capitalOptions = {
    "all": "Indiferente",
    "0": "No en la Capital",
    "1": "Capital"
};

export const provincesOptions = {
    "a_coruna": "A Coruña",
    "alava_araba": "Álava/Araba",
    "albacete": "Albacete",
    "alicante": "Alicante",
    "almeria": "Almería",
    "andorra": "Andorra",
    "asturias": "Asturias",
    "avila": "Ávila",
    "badajoz": "Badajoz",
    "barcelona": "Barcelona",
    "burgos": "Burgos",
    "caceres": "Cáceres",
    "cadiz": "Cádiz",
    "cantabria": "Cantabria",
    "castellon_castello": "Castellón/Castelló",
    "ceuta": "Ceuta",
    "ciudad_real": "Ciudad Real",
    "cordoba": "Córdoba",
    "cuenca": "Cuenca",
    "girona": "Girona",
    "granada": "Granada",
    "guadalajara": "Guadalajara",
    "guipuzcoa_gipuzkoa": "Guipúzcoa/Gipuzkoa",
    "huelva": "Huelva",
    "huesca": "Huesca",
    "islas_baleares_illes_balears": "Islas Baleares/Illes Balears",
    "jaen": "Jaén",
    "la_rioja": "La Rioja",
    "las_palmas": "Las Palmas",
    "leon": "León",
    "lleida": "Lleida",
    "lugo": "Lugo",
    "madrid": "Madrid",
    "malaga": "Málaga",
    "melilla": "Melilla",
    "murcia": "Murcia",
    "navarra_nafarroa": "Navarra/Nafarroa",
    "ourense": "Ourense",
    "palencia": "Palencia",
    "pontevedra": "Pontevedra",
    "salamanca": "Salamanca",
    "santa_cruz_de_tenerife": "Santa Cruz de Tenerife",
    "segovia": "Segovia",
    "sevilla": "Sevilla",
    "soria": "Soria",
    "tarragona": "Tarragona",
    "teruel": "Teruel",
    "toledo": "Toledo",
    "valencia": "Valencia",
    "valladolid": "Valladolid",
    "vizcaya_bizkaia": "Vizcaya/Bizkaia",
    "zamora": "Zamora",
    "zaragoza": "Zaragoza"
}

export const provincesOptions2 = {...provincesOptions, "all":"Media Total"}

export const typesOptions = {
    "all":"Indiferente",
    "piso":"Piso",
    "casa":"Casa",
    "chalet":"Chalet",
    "apartamento":"Apartamento",
    "atico":"Ático",
    "duplex":"Dúplex",
    "estudio":"Estudio",
    "loft":"Loft"
}

export const activityOptions = {
    "all": "Indiferente",
    "0": "Vendidos/Retirados",
    "1": "En Venta"
}

export const factsOptions = {
    "price_euro_mean_excluding_outliers": "Precio (€)",
    "superficie_construida_m2_mean_excluding_outliers": "Superficie Construida (m²)",
    "superficie_util_m2_mean_excluding_outliers": "Superficie Útil (m²)",
    "superficie_solar_m2_mean_excluding_outliers": "Superficie de Solar Media (m²)",
    "habitaciones_mean_excluding_outliers": "Número Habitaciones (ud)",
    "banos_mean_excluding_outliers": "Número de Baños (ud)",
    "gastos_de_comunidad_cleaned_mean_excluding_outliers": "Gastos de Comunidad (€)",
    "count": "Cantidad de inmuebles en venta (ud)",
    "price_per_m2": "Precio por m² (€)",
    "price_per_hab": "Precio por Habitación (€)",
    "price_per_wc": "Precio por Baño (€)"
}

export const categoryOptions = {
    "exterior_summary_no_pct": "Exterior No (%)",
    "exterior_summary_yes_pct": "Exterior Sí (%)",
    "vidrios_dobles_summary_no_pct": "Vidrios Dobles No (%)",
    "vidrios_dobles_summary_yes_pct": "Vidrios Dobles Sí (%)",
    "adaptado_a_personas_con_movilidad_reducida_summary_no_pct": "Adaptado Movilidad Reducida No (%)",
    "adaptado_a_personas_con_movilidad_reducida_summary_yes_pct": "Adaptado Movilidad Reducida Sí (%)",
    "puerta_blindada_summary_no_pct": "Puerta Blindada No (%)",
    "puerta_blindada_summary_yes_pct": "Puerta Blindada Sí (%)",
    "ascensor_summary_no_pct": "Ascensor No (%)",
    "ascensor_summary_yes_pct": "Ascensor Sí (%)",
    "balcon_summary_no_pct": "Balcón No (%)",
    "balcon_summary_yes_pct": "Balcón Sí (%)",
    "portero_automatico_summary_no_pct": "Portero Automático No (%)",
    "portero_automatico_summary_yes_pct": "Portero Automático Sí (%)",
    "garaje_summary_no_pct": "Garaje No (%)",
    "garaje_summary_yes_pct": "Garaje Sí (%)",
    "comedor_summary_no_pct": "Comedor No (%)",
    "comedor_summary_yes_pct": "Comedor Sí (%)",
    "terraza_summary_no_pct": "Terraza No (%)",
    "terraza_summary_yes_pct": "Terraza Sí (%)",
    "jardin_summary_no_pct": "Jardín No (%)",
    "jardin_summary_yes_pct": "Jardín Sí (%)",
    "armarios_empotrados_summary_no_pct": "Armarios Empotrados No (%)",
    "armarios_empotrados_summary_yes_pct": "Armarios Empotrados Sí (%)",
    "aire_acondicionado_summary_yes_pct": "Aire Acondicionado Sí (%)",
    "aire_acondicionado_summary_no_pct": "Aire Acondicionado No (%)",
    "trastero_summary_no_pct": "Trastero No (%)",
    "trastero_summary_yes_pct": "Trastero Sí (%)",
    "piscina_summary_no_pct": "Piscina No (%)",
    "piscina_summary_yes_pct": "Piscina Sí (%)",
    "chimenea_summary_no_pct": "Chimenea No (%)",
    "chimenea_summary_yes_pct": "Chimenea Sí (%)",
    "lavadero_summary_no_pct": "Lavadero No (%)",
    "lavadero_summary_yes_pct": "Lavadero Sí (%)",
    "soleado_summary_no_pct": "Soleado No (%)",
    "soleado_summary_yes_pct": "Soleado Sí (%)",
    "gas_summary_no_pct": "Gas No (%)",
    "gas_summary_yes_pct": "Gas Sí (%)",
    "amueblado_summary_no_pct": "Amueblado No (%)",
    "amueblado_summary_yes_pct": "Amueblado Sí (%)",
    "cocina_equipada_summary_no_pct": "Cocina Equipada No (%)",
    "cocina_equipada_summary_yes_pct": "Cocina Equipada Sí (%)",
    "calefaccion_summary_no_pct": "Calefacción No (%)",
    "calefaccion_summary_gas_natural_pct": "Calefacción Gas Natural (%)",
    "calefaccion_summary_gasoil_pct": "Calefacción Gasoil (%)",
    "calefaccion_summary_central_pct": "Calefacción Central (%)",
    "calefaccion_summary_otros_pct": "Calefacción Otros (%)",
    "calefaccion_summary_electrica_pct": "Calefacción Eléctrica (%)",
    "calefaccion_summary_gas_pct": "Calefacción Gas (%)",
    "conservacion_desconocido_pct": "Conservación Desconocida (%)",
    "conservacion_reformado_pct": "Conservación Reformado (%)",
    "conservacion_en_buen_estado_pct": "Conservación en Buen Estado (%)",
    "conservacion_a_reformar_pct": "Conservación a Reformar (%)",
    "conservacion_a_estrenar_pct": "Conservación a Estrenar (%)",
    "antiguedad_desconocido_pct": "Antigüedad Desconocida (%)",
    "antiguedad_mas_de_50_anos_pct": "Antigüedad Más de 50 Años (%)",
    "antiguedad_entre_20_y_30_anos_pct": "Antigüedad entre 20 y 30 Años (%)",
    "antiguedad_entre_10_y_20_anos_pct": "Antigüedad entre 10 y 20 Años (%)",
    "antiguedad_entre_30_y_50_anos_pct": "Antigüedad entre 30 y 50 Años (%)",
    "antiguedad_menos_de_5_anos_pct": "Antigüedad Menos de 5 Años (%)",
    "antiguedad_entre_5_y_10_anos_pct": "Antigüedad entre 5 y 10 Años (%)",
    "carpinteria_exterior_cleaned_desconocido_pct": "Carpintería Exterior Desconocida (%)",
    "carpinteria_exterior_cleaned_aluminio_pct": "Carpintería Exterior Aluminio (%)",
    "carpinteria_exterior_cleaned_climalit_pct": "Carpintería Exterior Climalit (%)",
    "carpinteria_exterior_cleaned_pvc_pct": "Carpintería Exterior PVC (%)",
    "carpinteria_exterior_cleaned_otros_pct": "Carpintería Exterior Otros (%)",
    "carpinteria_exterior_cleaned_madera_pct": "Carpintería Exterior Madera (%)",
    "tipo_suelo_summary_gres_pct": "Tipo de Suelo Gres (%)",
    "tipo_suelo_summary_tarima_flotante_pct": "Tipo de Suelo Tarima Flotante (%)",
    "tipo_suelo_summary_desconocido_pct": "Tipo de Suelo Desconocido (%)",
    "tipo_suelo_summary_otros_pct": "Tipo de Suelo Otros (%)",
    "tipo_suelo_summary_terrazo_pct": "Tipo de Suelo Terrazo (%)",
    "tipo_suelo_summary_parquet_pct": "Tipo de Suelo Parquet (%)",
    "tipo_suelo_summary_marmol_pct": "Tipo de Suelo Mármol (%)",
    "tipo_suelo_summary_ceramica_pct": "Tipo de Suelo Cerámica (%)",
    "cocina_summary_desconocido_pct": "Cocina Desconocida (%)",
    "cocina_summary_otros_pct": "Cocina Otros (%)",
    "cocina_summary_independiente_pct": "Cocina Independiente (%)",
    "cocina_summary_individual_pct": "Cocina Individual (%)",
    "cocina_summary_americana_pct": "Cocina Americana (%)",
    "cocina_summary_amueblada_pct": "Cocina Amueblada (%)",
    "orientacion_summary_desconocido_pct": "Orientación Desconocida (%)",
    "orientacion_summary_noreste_pct": "Orientación Noreste (%)",
    "orientacion_summary_otros_pct": "Orientación Otros (%)",
    "orientacion_summary_sur_pct": "Orientación Sur (%)",
    "orientacion_summary_noroeste_pct": "Orientación Noroeste (%)",
    "orientacion_summary_norte_pct": "Orientación Norte (%)",
    "orientacion_summary_sureste_pct": "Orientación Sureste (%)",
    "orientacion_summary_oeste_pct": "Orientación Oeste (%)"
}